---

# Installing EPEL repository on a CentOS Linux and RHEL 7. x
- name: Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release.noarch
    state: latest

#Installing nginx on a CentOS Linux
- name: Install NGINX
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
  notify: start-nginx

# copy general config NGINX
- name: Create general config NGINX
  become: true
  template:
    src: "template/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0755
  #notify: reload-nginx
  tags: install nginx
