# Set global options
data_dir = "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
[api]
enabled = false
# address = "127.0.0.1:8686"

# Ingest data by tailing one or more files
[sources.in]
type = "journald"

# Send structured data to a short-term storage
[sinks.out]
type = "clickhouse"
inputs = [ "in" ]
endpoint = "http://localhost:8123"
database = "logs"
table = "journald"
