---
ansible_user_id: dvps
ansible_id_rsa: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqN7xG12F6yjf4aA/11L60FKXVEGkR8T+sByW1G4xkUTsCD4z4src/pDs59yMlZJu83r477u0ubNE2my5Vu2P6wnedvWBEiCgNHf71uvZR4THgG+4N1Bt8jVQmLghC0FdPtVjpcHGjdT0ThUOUW+BN7MQ4Zaq1Rl13gBXdkOXq4/8OfDEJ/qvTbc86VJk9eko9tQuAAqGFZKGWullabZQID7OPnnRPgIOHlCVxIBlNFUgQTnaKH6gKnMA330kBXwa3RBxgF9h4LtujNLUQ7ea7J8qoXTBP0bSRUAjgOcLcPHPTUU7hnBgFtpixNcGrQ/WjvH1VV0Faq+UyhxlN86l+CPC+INyALau6Pl0NczSiBx3wxRfexWYccJ9iJoD1o6xNTr5aPW42bSLqqV9ldW0nuHFbI6B3m4XlImQYp93vi+uQsMhgqGMvF6Z/fJ8Mcu1XXN4Lp8iSczk4HuPsbiXUlH5hWeeNKLEw8K9XmoEygFTsmWllwbop5b5NYrH41E0= ans@ansible
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
