# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: postgres 
#   namespace: stage
#   labels:
#     app: database

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          # volumeMounts:
          #   - name: postgres-vol
          #     mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /data/pgdata
      # volumes:
      #   - name: postgres-vol
      #     emptyDir: {}
  #       accessModes: ["ReadWriteMany"]
  #       resources:
  #         requests:
  #           storage: 1Gi

  # volumeMounts:
  #       - mountPath: "/tmp/cache"
  #         name: my-volume
  

---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  # type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-db-disks
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi