apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:stable
        # volumeMounts:
        #     - name: frontend-vol
        #       mountPath: /data
        resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        ports:
        - containerPort: 80
      # volumes:
      #     - name: frontend-vol
      #       emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30060
  selector:
    app: frontend

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: frontend-disk
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi